feat: support static action forms with layout
ForestAdmin/agent-nodejs pull request #1182
Opened 2024-09-25 12:35 UTC by realSpok

## Definition of Done
#86c097c1w
### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2024-09-27 08:50 UTC, EnkiP commented on packages/datasource-customizer/test/decorators/actions/collection.test.ts
>      test('should compute the form recursively', async () => {
keep this test with dynamic elements in a row in a page

2024-09-27 09:06 UTC, EnkiP requested changes
...

2024-09-27 11:48 UTC, EnkiP approved these changes

2024-09-27 11:49 UTC, EnkiP requested changes
sry missclick again :/ need recursive check in getForms

2024-09-27 15:19 UTC, realSpok commented on packages/datasource-customizer/src/decorators/actions/collection.ts
>              Object.values(field).some(value => this.isHandler(value)) ||
yes.  I will wait for the pages to be available I think

2024-10-07 15:08 UTC, EnkiP approved these changes

2024-10-07 15:39 UTC, merged