feat(decorator): allow to rename a collection
ForestAdmin/agent-nodejs pull request #341
Opened 2022-06-09 12:45 UTC by Scra3

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2022-06-09 19:59 UTC, romain-gilliotte requested changes

2022-06-09 19:59 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/decorators/rename-collection/collection.ts
> +  private substitutedName: string;
`refineSchema` implementation is missing.

This will break relations that are defined by the datasource (emulated relations will work)

2022-06-09 19:59 UTC, romain-gilliotte commented on packages/agent/src/builder/decorators-stack.ts
>    rename: DataSourceDecorator<RenameCollectionDecorator>;
no need to inject in the stack

2022-06-09 19:59 UTC, romain-gilliotte commented on docs/datasources/README.md
> +By provided options when plugin a data source, you can specify which entities should get loaded.
Correct english is actually `plugging`

https://dictionary.cambridge.org/dictionary/english/plugging

2022-06-09 19:59 UTC, romain-gilliotte commented on docs/datasources/README.md
> +Take note that data sources are defined in independent NPM packages (here `@forestadmin/datasource-sql`).
good catch

2022-06-10 07:21 UTC, Scra3 commented on packages/_example/src/index.ts
> +  await fastifyAppV2.listen(Number(process.env.HTTP_PORT_FASTIFY_V2));
yes

2022-06-10 07:24 UTC, Scra3 commented on packages/_example/src/index.ts
> +  await fastifyAppV2.listen(Number(process.env.HTTP_PORT_FASTIFY_V2));
listen(port: number | string, address?: string, backlog?: number): Promise<string>;

2022-06-10 07:24 UTC, Scra3 commented on packages/agent/src/builder/decorators-stack.ts
>    rename: DataSourceDecorator<RenameCollectionDecorator>;
Yeah, i have forgot to remove it

2022-06-10 14:50 UTC, Scra3 commented on packages/datasource-toolkit/src/decorators/rename-collection/collection.ts
> +export default class RenameCollectionCollectionDecorator extends CollectionDecorator {
https://github.com/ForestAdmin/agent-nodejs/pull/344

2022-06-13 11:48 UTC, Scra3 commented on packages/datasource-toolkit/src/decorators/rename-collection/collection.ts
> +export default class RenameCollectionCollectionDecorator extends CollectionDecorator {
merged

2022-06-15 11:34 UTC, romain-gilliotte approved these changes

2022-06-15 11:49 UTC, merged