Cu 2f7f05g new agent   add documentation on import field with write capabilities alban bertolini
ForestAdmin/agent-nodejs pull request #362
Opened 2022-06-29 15:24 UTC by Scra3

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2022-07-22 12:27 UTC, romain-gilliotte requested changes
can you re-add the readonly flag?

it avoids needing to

2022-07-22 12:27 UTC, romain-gilliotte commented on packages/agent/src/builder/collection.ts
> +    this.stack.write.getCollection(this.name).replaceFieldWriting(name, value => {
You don't know that the source field is writable.
this needs to be checked in the schema and throw otherwise

2022-07-22 12:27 UTC, romain-gilliotte commented on docs/agent-customization/fields/computed.md
> +collection.importField('city', { path: 'address:city' });
i think the readonly option was useful

it prevents customers from writing this:
```importField().replaceFieldWriting().importField().replaceFieldWriting()```

2022-07-22 14:37 UTC, Scra3 commented on packages/agent/src/builder/collection.ts
> +    this.stack.write.getCollection(this.name).replaceFieldWriting(name, value => {
good catch

2022-07-22 14:41 UTC, Scra3 commented on docs/agent-customization/fields/computed.md
> +collection.importField('city', { path: 'address:city' });
I will add an other PR, because it is already removed.

2022-07-26 08:40 UTC, romain-gilliotte approved these changes

2022-07-26 08:42 UTC, merged