docs(s3): add an example to document how to upload a file to s3
ForestAdmin/agent-nodejs pull request #368
Opened 2022-07-05 16:14 UTC by Scra3

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2022-07-07 08:06 UTC, jeffladiray requested changes

2022-07-07 08:06 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +This example show how to upload a file to an S3 bucket.
```suggestion
This example shows how to upload a file to a S3 bucket.
```

2022-07-07 08:06 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +You can copy/past this custom AWS service in your agent to use it.
```suggestion
You can copy/paste this custom AWS service in your agent to use it.
```

2022-07-07 08:06 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +Our data uri is not conventional because we have added the file name.
```suggestion
Our data uri are not conventional because we have added the file name.
```

2022-07-07 08:06 UTC, jeffladiray commented on docs/SUMMARY.md
> +  - [Upload to AWS S3 Bucket](agent-customization/examples/upload-file-to-s3.md)
Maybe a new section dedicated to example could be nice

2022-07-07 13:58 UTC, Scra3 commented on docs/SUMMARY.md
> +  - [Upload to AWS S3 Bucket](agent-customization/examples/upload-file-to-s3.md)
yeah ok :)

2022-07-18 07:52 UTC, jeffladiray requested changes
Should be good after this one :)

2022-07-18 07:52 UTC, jeffladiray commented on docs/SUMMARY.md
> +- [Upload to AWS S3 Bucket](agent-customization/examples/upload-file-to-s3.md)
```suggestion
- [Upload a file to S3](agent-customization/examples/upload-file-to-s3.md)
```

(I'm a bit picky, but this is the filename containing the doc. It's a bit easier to find which file is which when the title is the same as the filename)

2022-07-18 07:52 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +## Add a method to decode the date uri given by the client
```suggestion
## Add a method to decode the data URI given by the client
```

2022-07-18 07:52 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +url of the avatar.
```suggestion
URL of the avatar.
```

Also, I'm not sure why this isn't on the same line

2022-07-18 07:52 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +        // get the path stored in s3. The `pathname` is started with `/` that's why we need to remove it.
```suggestion
        // get the path stored in s3. The `pathname` starts with a `/`, that's why we need to remove it.
```

2022-07-18 07:52 UTC, jeffladiray commented on docs/agent-customization/examples/upload-file-to-s3.md
> +    // compute an unique path to avoid colision when uploading the same file twice for a different record.
```suggestion
    // compute an unique path to avoid collision when uploading the same file twice for a different record.
```

2022-07-25 07:08 UTC, jeffladiray approved these changes

2022-07-25 07:13 UTC, merged