fix(datasource-sequelize): handle compatibility with sequelize 6.2
ForestAdmin/agent-nodejs pull request #378
Opened 2022-07-25 12:22 UTC by jeffladiray

## Definition of Done

### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [x] Ensure that Types have been updated according to your changes (if needed)

### Security

- [x] Consider the security impact of the changes made

2022-07-26 07:43 UTC, arnaud-moncel requested changes

2022-07-26 07:43 UTC, arnaud-moncel commented on packages/datasource-sequelize/src/utils/un-ambigous.ts
>        .getAttributes()[relationFieldName].field;
missing change here 😅

2022-07-26 13:28 UTC, arnaud-moncel approved these changes

2022-08-04 16:01 UTC, jeffladiray commented
I'm closing this, as another issue was spotted during the manual tests with @arnaud-moncel.
This is not worth an epic, but it is still a big topic that needs functionnal testing to make sure that no regression will be introduced in the future + to ease compatibility increase in the future

2022-08-04 16:01 UTC, closed without merging