feat(smart-action): users can now display html when an error occurs
ForestAdmin/agent-nodejs pull request #403
Opened 2022-09-01 15:17 UTC by SteveBunlon

## Definition of Done

### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [x] Consider the security impact of the changes made

2022-09-01 15:18 UTC, SteveBunlon commented
This PR is not finished yet

2022-09-02 07:21 UTC, romain-gilliotte requested changes
If the frontend supports the same for errors and success, please reuse the `SuccessResult` type for both errors and success (rename it to `DisplayResult`) and factorize everything

2022-09-02 07:21 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/decorators/actions/result-builder.ts
> +  error(message?: string, html?: string): ActionResult {
Please use the same syntax than for success (first param is the message, second param is options).

2022-09-02 07:23 UTC, romain-gilliotte commented
> This PR is not finished yet

We use github draft on this repo when a PR is not ready :)
I changing the state of this one to draft

2022-09-02 08:45 UTC, SteveBunlon commented on packages/datasource-toolkit/src/decorators/actions/result-builder.ts
> +  error(message?: string, html?: string): ActionResult {
By looking at the success code, you can only customise message OR html, not both. That's a problem. Any insight ?

2022-09-02 13:59 UTC, SteveBunlon commented on docs/agent-customization/actions/responses.md
> +
Screenshot missing here

2022-09-12 11:40 UTC, romain-gilliotte requested changes

2022-09-12 11:40 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/decorators/actions/result-builder.ts
> +  success(message?: string, options?: { html?: string; invalidated?: string[] }): ActionResult {
can we rename `message` to `toasterMessage`
and `options.html` to `options.sidePanelHtml`?

Something like this:
```
  /**
   * Returns a success response from the action
   * @param toasterMessage the success message to display on the toaster
   * @param options.sidePanelHtml in addition to the toaster, you may open a side-panel to display
   *   the result in HTML
   * @param options.invalidated for summary views, list of relationships that should be reloaded
   * @example
   * .success('Success', { sidePanelHtml: '<blinkee>Success!</blinkee>' });
   */
  success(
    toasterMessage?: string,
    options?: { sidePanelHtml?: string; invalidated?: string[] },
  ): ActionResult {
    return {
      type: 'Success',
      message: toasterMessage ?? 'Success',
      invalidated: new Set(options?.invalidated ?? []),
      html: options?.sidePanelHtml,
    };
  }

  /**
   * Returns an error response from the action
   * @param toasterMessage the error message to return
   * @param options.sidePanelHtml in addition to the toaster, you may open a side-panel to display
   *   the result in HTML
   * @example
   * .error('Failed to refund the customer!', { sidePanelHtml: '<strong>Error!</strong>' });
   */
  error(toasterMessage?: string, options?: { sidePanelHtml: string }): ActionResult {
    return {
      type: 'Error',
      message: toasterMessage ?? 'Error',
      html: options?.sidePanelHtml,
    };
  }
```

2022-09-12 11:40 UTC, romain-gilliotte commented on docs/agent-customization/actions/responses.md
> +  { type: 'html' },
doc is not up-to-date with changes made on other files

2022-09-13 08:46 UTC, SteveBunlon commented on docs/agent-customization/actions/responses.md
> +
Screenshot added 👌

2022-09-13 08:50 UTC, SteveBunlon commented on docs/agent-customization/actions/responses.md
> +  { type: 'html' },
updated 🆗

2022-09-15 10:50 UTC, romain-gilliotte approved these changes

2022-09-15 13:22 UTC, merged