fix(condition-tree): longer than and shorter than operators are supported
ForestAdmin/agent-nodejs pull request #415
Opened 2022-09-08 15:42 UTC by Scra3

…rted

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2022-09-08 16:04 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/validation/condition-tree.ts
> +    if (operator !== 'ShorterThan' && operator !== 'LongerThan') {
That's also the case for other operators

BeforeXDaysAgo is on date, but the value the operator expects is an integer

2022-09-09 07:14 UTC, Scra3 commented on packages/datasource-toolkit/src/validation/condition-tree.ts
> +    if (operator !== 'ShorterThan' && operator !== 'LongerThan') {
👍

2022-09-09 07:34 UTC, Scra3 commented on packages/datasource-toolkit/src/validation/rules.ts
> +  Date: ['Date', ValidationPrimaryTypes.Null],
Not really sure but Number should not be accepted.

2022-09-12 08:10 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/validation/rules.ts
> +  Date: ['Date', ValidationPrimaryTypes.Null],
previous bug fix for AfterXHoursAgo

2022-09-12 08:13 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/validation/rules.ts
> +  ],
you can remove shorterthan and longerthan

2022-09-12 08:14 UTC, romain-gilliotte requested changes
Now that the validator is fixed, can you call it at the following line?

https://github.com/ForestAdmin/agent-nodejs/blob/beta/packages/datasource-toolkit/src/decorators/validation/collection.ts#L62

2022-09-12 10:06 UTC, romain-gilliotte approved these changes

2022-09-12 10:07 UTC, merged