Perf/use lighter endpoint for permissions
ForestAdmin/agent-nodejs pull request #421
Opened 2022-09-12 13:55 UTC by ghusse

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)
- [ ] Ensure that Types have been updated according to your changes (if needed)

### Security

- [ ] Consider the security impact of the changes made

2022-09-22 13:24 UTC, Thenkei reviewed
Ongoing

2022-09-22 13:24 UTC, Thenkei commented on packages/agent/src/agent/services/authorization/internal/action-permission.ts
> +    });
❔ Why not using the LRU `fetchMethod` to automatically get permissions per rendering?

2022-09-22 13:24 UTC, Thenkei commented on packages/agent/src/agent/services/authorization/internal/action-permission.ts
> +  }
I'm a little bit lost here. We have `EnvironmentPermissions` but we put them for a `renderingId` (team). 🤯

2022-09-27 07:12 UTC, ghusse commented on packages/agent/src/agent/services/authorization/authorization.ts
> +      context.throw(403, 'Forbidden');
You're right, I'll apply the suggestion because it's a lot simpler to use like that

2022-09-27 07:13 UTC, ghusse commented on packages/agent/src/agent/services/authorization/internal/action-permission.ts
> +    });
To be honest, I discovered this function while doing my second PR. For this one I just used the same method used previously in the code.

2022-09-27 07:20 UTC, ghusse commented on packages/agent/src/agent/services/authorization/internal/action-permission.ts
> +  }
You're totally right. I should remove this and only have one cache value. Thanks a lot

2022-09-28 09:46 UTC, Thenkei requested changes
- ✅&nbsp; Code review - Perfecto. I really like the improvements and clarity you've added. 👌 
  - ✅&nbsp; Performance concerns
  - ✅&nbsp; Security concerns
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; The PR tackle one subject only
- ✅  Automatic tests
  - ✅  Unit tests
- 🔴  Manual tests - I've started a new project in development env the backend is re-called every time I browse to a collection. See the screenshot below
- ✅  PR title
- ✅  Destination branch

![Screenshot 2022-09-28 at 11 43 05](https://user-images.githubusercontent.com/6266091/192746960-20c8974b-00b0-48a9-a6b5-e12a3b62ebf7.png)

2022-09-28 09:52 UTC, Thenkei commented on packages/agent/src/services/authorization/internal/action-permission.ts
> +      this.permissionExpirationTimestamp < Date.now()
```suggestion
      this.permissionExpirationTimestamp > Date.now()
```

2022-09-28 09:56 UTC, Thenkei commented on packages/agent/src/services/authorization/internal/action-permission.ts
> +      this.permissionExpirationTimestamp < Date.now()
Indeed, it works with this fix.

⚠️ We need to add a test on this TTL mechanism or even wrap it in some utils.

2022-09-28 12:23 UTC, Thenkei approved these changes

2022-09-28 12:28 UTC, merged