fix(options): use should not be able to set a too small permissions cache duration
ForestAdmin/agent-nodejs pull request #453
Opened 2022-09-28 12:24 UTC by Thenkei

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2022-09-29 19:50 UTC, romain-gilliotte requested changes
Can you log a warning to tell the user that his setting is getting ignored?

2022-10-03 07:57 UTC, Thenkei commented
> Can you log a warning to tell the user that his setting is getting ignored?

You're right, I will rework it. 💪

2022-10-28 06:59 UTC, romain-gilliotte approved these changes

2022-10-28 06:59 UTC, romain-gilliotte requested changes
rebase + to main

2022-11-02 11:51 UTC, romain-gilliotte approved these changes

2022-11-02 11:52 UTC, merged