feat: allow including/excluding collection when adding datasources
ForestAdmin/agent-nodejs pull request #462
Opened 2022-10-03 09:06 UTC by romain-gilliotte

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2022-10-03 16:26 UTC, SteveBunlon commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +export default class PublicationCollectionDataSourceDecorator extends DataSourceDecorator<PublicationFieldCollectionDecorator> {
I don't understand the choice of `PublicationCollectionDataSourceDecorator` can you explain please ? (I mean, the naming)

2022-10-03 16:26 UTC, SteveBunlon commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +          collection.changeFieldVisibility(fieldName, false);
Is there a reason why we simply set the visibility to false, and not delete it entirely ?

2022-10-03 16:26 UTC, SteveBunlon commented on packages/datasource-customizer/src/datasource-customizer.ts
> +        const publicationDecorator = new PublicateCollectionDataSourceDecorator(dataSource);
I don't understand Publicate here

2022-10-04 10:16 UTC, SteveBunlon requested changes
Could be great to have some tests with the include option, to assert that only the provided collection are being kept in the file `packages/datasource-customizer/test/datasource-customizer.test.ts`.

2022-10-04 10:16 UTC, SteveBunlon commented on docs/datasources/connection/relationships.md
> +Adding as many datasources as you need is good, inter-connecting them together is better.
This is maybe a change you had in mind before this PR. Just to point this out, this does not look to be related to this PR. Is this change intended ?

2022-10-04 10:16 UTC, SteveBunlon commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +    }
This means that exclude and include can both be used ?

2022-10-04 10:16 UTC, SteveBunlon commented on packages/datasource-customizer/test/decorators/publication-collection/datasource.test.ts
> +        'myLibrary',
Shouldn't it be `myBooks` here ?

2022-10-04 15:00 UTC, romain-gilliotte commented on packages/datasource-customizer/src/datasource-customizer.ts
> +        const publicationDecorator = new PublicateCollectionDataSourceDecorator(dataSource);
I renamed it to `keepCollectionsMatching`
Publicate does not exists in english... that's badly translated french

2022-10-04 15:04 UTC, romain-gilliotte commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +    }
Yep. Not super useful though.

`addDataSource(..., { include: ['steve', 'romain'], exclude: ['romain'] })`
=> Keep only steve

In the initial spec we did months ago we wanted to support regexp matching, which would make a lot more sense but I did not implement it because I got lazy.

`addDataSource(..., { include: [/^payfit_/], exclude: ['payfit_credit_cards'] })`
=> Keep all collection prefixed with `payfit_` but not 'payfit_credit_cards'

2022-10-04 15:13 UTC, romain-gilliotte commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +          collection.changeFieldVisibility(fieldName, false);
It's more complicated than that, we can do a meet.

There is a different schema for each layer in the decorator stack.
This tells that all layers on top of us won't have that field in the schema

2022-10-04 15:14 UTC, romain-gilliotte commented on packages/datasource-customizer/test/decorators/publication-collection/datasource.test.ts
> +        'myLibrary',
good catch

2022-10-04 15:17 UTC, romain-gilliotte commented on docs/datasources/connection/relationships.md
> +Adding as many datasources as you need is good, inter-connecting them together is better.
It was intended but you're right it is not really related.

My issue was that this PR was introducing a new option to `addDataSource`, and that
- all documented options were under the `Multiple Datasources` section.
- this new option is not strictly related to customer in that situation

=> I refactored this part of the doc

2022-10-04 15:24 UTC, romain-gilliotte commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +          collection.changeFieldVisibility(fieldName, false);
if you look at the `delete` call on line 35, it's actually the same:
we're removing the field only from our layer (we're deleting in `this`).

So underlying layers don't know

2022-10-04 15:26 UTC, romain-gilliotte commented on docs/datasources/connection/partial-imports.md
> +```
😱

2022-10-05 10:53 UTC, SteveBunlon approved these changes
Tested on the test agent, works like a charm ❇️

2022-10-05 10:53 UTC, SteveBunlon commented on docs/datasources/connection/relationships.md
> +Adding as many datasources as you need is good, inter-connecting them together is better.
Roger that.

2022-10-05 10:53 UTC, SteveBunlon commented on packages/datasource-customizer/src/decorators/publication-collection/datasource.ts
> +    }
Let's keep it that way, the regexp way serves edge cases, that can still be achieved by only providing static include exclude. KISS.

2022-10-05 10:54 UTC, merged