feat(datasource-sql): add advanced options on createSqlDataSource
ForestAdmin/agent-nodejs pull request #495
Opened 2022-10-14 13:08 UTC by romain-gilliotte

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2022-10-17 13:59 UTC, SteveBunlon commented on packages/datasource-sql/src/index.ts
> +import { DatabaseConnectionOptions as ConnectionOptions } from './types';
I find ConnectionOptions self explanatory, naming it like this directly from the type is ok IMO.

2022-10-17 14:02 UTC, SteveBunlon requested changes
I don't how much time that would took, but having an additional datasource on the test agent would be awesome, just to see the new way of creating connections in action

2022-10-17 14:02 UTC, SteveBunlon commented on packages/datasource-sql/src/types.ts
> +export type DatabaseConnectionOptions =
I'm pretty sure you have a reason, however I would like to understand. 

Why are we picking up only certain options ? Couldn't we let the user use everything provided / authorized by sequelize ?

2022-10-18 10:49 UTC, romain-gilliotte commented on packages/datasource-sql/src/index.ts
> +import { DatabaseConnectionOptions as ConnectionOptions } from './types';
done

2022-10-18 11:07 UTC, romain-gilliotte commented on packages/datasource-sql/src/types.ts
> +export type DatabaseConnectionOptions =
I removed options that:
- Would prevent us from migrating to another ORM or to a newer version of sequelize (`define`, ...)
- Duplicate functionality (`hook`, `typeValidation`, ...)
- Did not make sense in the scope of the sql-connector (`operatorAliases`, `quoteIdentifiers`, ...)

Because I know that some customers like to be able to still do those things (accepting that it risks breaking the build in the future when we upgrade the lib), they can simply use a cast.

But I don't want it to be officially supported.

`createSqlDataSource({typeValidation: true} as ConnectionOptions)` will work, and do what you expect.

2022-10-18 12:39 UTC, SteveBunlon commented on packages/datasource-sql/src/types.ts
> +export type DatabaseConnectionOptions =
ok copy that chief

2022-10-19 12:25 UTC, SteveBunlon approved these changes

2022-10-19 12:26 UTC, merged