feat: import all fields
ForestAdmin/agent-nodejs pull request #510
Opened 2022-10-21 13:38 UTC by Scra3

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2022-10-24 09:02 UTC, romain-gilliotte commented on packages/datasource-toolkit/src/utils/schema.ts
> +  static getColumns(schema: CollectionSchema): string[] {
This duplicates the code of `ProjectionFactory.columns`

2022-10-24 09:33 UTC, Scra3 commented on packages/datasource-toolkit/src/utils/schema.ts
> +  static getColumns(schema: CollectionSchema): string[] {
done

2022-10-26 07:45 UTC, romain-gilliotte requested changes

2022-10-26 07:45 UTC, romain-gilliotte commented on packages/plugin-import-fields/src/index.ts
> +export default async function importFields<
You are using templated types, but I'm not sure that this actually works as the `.use` method is not calling them.

Did you find a way to make autocompletion work when customizing the agent?
If not, I think we would be better off saying that `relationName` is simply a string (and the same for the others)

2022-10-26 09:48 UTC, romain-gilliotte commented on docs/SUMMARY.md
> +  - [Import all the fields](agent-customization/plugins/import-fields.md)
other plugins are in a folder

2022-10-27 06:31 UTC, Scra3 commented on packages/plugin-import-fields/src/index.ts
> +    const supportedFormatByFrontend = `${relationName}_${column}`;
it does not work because the front transform @@@ by a camelcase when it getting the list.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/16675775/198208265-1c367972-2fdd-446d-aab0-2e5032dd57bd.png">

2022-10-27 08:23 UTC, romain-gilliotte commented on packages/plugin-import-fields/src/index.ts
> +    const supportedFormatByFrontend = `${relationName}_${column}`;
https://github.com/ForestAdmin/forest-express-mongoose/blob/main/src/services/flattener.js#L6

2022-10-27 08:31 UTC, romain-gilliotte approved these changes

2022-10-27 09:00 UTC, merged