feat(webhook-custom-actions): use webhook nocode smart actions configured in the frontend
ForestAdmin/agent-nodejs pull request #671
Opened 2023-04-18 08:39 UTC by ghusse

Linked to CU-860qgzbzg

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-04-18 09:59 UTC, Thenkei requested changes
Romain made a few comments. Let's talk about it if you want.

2023-04-18 09:59 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/types.ts
> +export type ModelCustomization<TConfiguration> = {
no default value is provided (use unknown)

2023-04-18 09:59 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/types.ts
> +export enum ActionScope {
we don't use enums (save a lots of imports)

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
take care this is wrong.

As we were asked to implement it a global action is the same than bulk + select all.
That means that when running the action on a segment, only the segment is considered.

If we change those semantics, the documentation is wrong

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +export default function createWebhookExecutor<S extends TSchema = TSchema>(
I suppose you do this so that you can add the action directly.
We tend to avoid indirection

Something in the lines of
```
for (const action of actions)
  addAction(ctx => executeWebhook(action, ctx))
```

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +    case 'global':
see comment bellow for global (what happens in a segment?)

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +      if (ids.length !== 1) {
useless check

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +          id: ids[0],
the primary key is not always named id

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
IIRC getRecordIds will throw an error on collection using a composite primary key
I think you need to handle those cases as well

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/action-customization.ts
> +function translateScope(scope: `${ConfigurationScope}`): ActionScope {
why not use the ActionScope type in the first place?

2023-04-18 09:59 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-with-cache.ts
> +  async getConfiguration(): Promise<ModelCustomization<unknown>[]> {
useless cache pattern
the method is called only once

2023-04-18 09:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/action-customization.ts
> +      collection.addAction(action.name, {
This is using the same customizer than the one that is used by the customer to code.
This means that the customer can **code** smart actions that can depend on smart actions that were defined in the frontend.

Not a big deal for smart actions (will just break those actions), but will be for fields (will prevent the server from starting).

```
// we may want to prevent the customer from being able to do that
collection.addAction('myaction-in-code', {
  execute: (ctx) => {
    return ctx.collection.execute('no-code-action-from-backend');
  }
})
````

IMO, we can not care for now.
When we develop the smart fields we'll stack another customizer on top of the current one for no code stuff

2023-04-18 11:07 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/types.ts
> +export enum ActionScope {
Enums are not used In other types : we only declare strings that can take the values of enums. From my point of view it combines the best of both worlds.

2023-04-18 11:08 UTC, ghusse commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
Are you sure?

2023-04-18 11:09 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/model-customization-with-cache.ts
> +  async getConfiguration(): Promise<ModelCustomization<unknown>[]> {
For the moment yes, but we will introduce other customizations soon

2023-04-18 11:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
@romain-gilliotte seems pretty sure about that.

2023-04-18 11:59 UTC, Thenkei commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
Let's run a test to re-ensure ourself ?

2023-04-18 13:51 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/types.ts
> +export enum ActionScope {
Done anyway

2023-04-18 13:52 UTC, ghusse commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +  const ids = action.configuration.scope === 'global' ? [] : await context.getRecordIds();
I changed it for now

2023-04-18 13:52 UTC, ghusse commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +export default function createWebhookExecutor<S extends TSchema = TSchema>(
I changed it, I still need to simplify the interface but the idea is here

2023-04-18 13:52 UTC, ghusse commented on packages/agent/src/services/model-customizations/webhook-executor.ts
> +          id: ids[0],
OMG, you're right.

I fixed this in the latest changes

2023-04-18 13:54 UTC, ghusse commented on packages/agent/src/services/model-customizations/action-customization.ts
> +function translateScope(scope: `${ConfigurationScope}`): ActionScope {
The API uses `single`, `global` and `bulk` everywhere, whereas the agent uses `Single`, `Global` and `Bulk` with a capital first letter :'(

In addition to that, `ActionScope` is declared in the `datasource-toolkit` which is not a dependency of `forestadmin-client`.

2023-04-18 13:54 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/model-customization-with-cache.ts
> +  async getConfiguration(): Promise<ModelCustomization<unknown>[]> {
I removed this premature optimization

2023-04-19 11:50 UTC, Thenkei commented on packages/agent/src/services/model-customizations/execute-webhook.ts
> +  const records = await context.getRecords(primaryKeys);
👌 Super clean !

2023-04-19 12:12 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +          configuration.scope.slice(1)) as ActionScope)
🐐

2023-04-19 12:23 UTC, Thenkei commented on packages/datasource-customizer/src/context/relaxed-wrappers/collection.ts
> +
I would have preferred a higher API level getter.

Something like:
```
get getPrimaryKeys() {
  return SchemaUtils.getPrimaryKeys(this.collection.schema);
}
```

2023-04-19 12:24 UTC, Thenkei commented on packages/datasource-customizer/src/context/relaxed-wrappers/collection.ts
> +
But I guess that your version offers more possibilities in the end.

2023-04-19 12:28 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +    ...configuration,
```suggestion
  const mappedConfiguration: WebhookActionConfiguration = {
    ...modelCustomization.configuration,
```

2023-04-19 12:29 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +  async getConfiguration(): Promise<WebhookAction[]> {
```suggestion
  async getConfiguration(): Promise<ModelCustomization[]> {
```

2023-04-19 12:30 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +    const result = await ServerUtils.query<ModelCustomization<WebhookActionConfigurationApi>[]>(
```suggestion
    const result = await ServerUtils.query<ModelCustomization[]>(
```

2023-04-19 12:30 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +): ModelCustomization<WebhookActionConfiguration> {
```suggestion
function mapApiValues(modelCustomization: ModelCustomization): ModelCustomization {
```

2023-04-19 12:32 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +  async getConfiguration(): Promise<WebhookAction[]> {
I set this type on purpose, because today we only have one type that can be returned by this function.

2023-04-19 12:33 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +    const result = await ServerUtils.query<ModelCustomization<WebhookActionConfigurationApi>[]>(
This is also intentional here because we can only have one type here.

2023-04-19 12:33 UTC, ghusse commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +): ModelCustomization<WebhookActionConfiguration> {
Same here

2023-04-19 12:42 UTC, Thenkei commented on packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
> +  async getConfiguration(): Promise<WebhookAction[]> {
Well that weird since the interface says `ModelCustomization[]`

2023-04-19 12:43 UTC, Thenkei approved these changes
- ✅&nbsp;Code review
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; Performance concerns
  - ✖️&nbsp; Security concerns
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
  - ✅&nbsp; Integration tests
-✖️&nbsp;Manual tests
- ✅&nbsp;PR title
- ✅&nbsp;Destination branch
- ✅&nbsp;PR linked to the clickup task

2023-04-20 06:57 UTC, merged