feat(datasource-sql): add an ssh client when a user provide ssh options
ForestAdmin/agent-nodejs pull request #730
Opened 2023-06-14 11:03 UTC by Scra3

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-06-21 15:16 UTC, romain-gilliotte requested changes

2023-06-21 15:16 UTC, romain-gilliotte commented on packages/datasource-sql/src/connection/services/ssh-tunnel.ts
> +        this.sourceHost,
IMHO, you should leave those null.

if I read the code correctly, you are setting them to 'localhost' and the random port that the local reverse proxy has chosen automatically.
I don't see what the SSH server could possibly do with that information (it's not reachable at all from there), which makes me think that this either

- not used in any way
- used for something else

2023-06-21 15:16 UTC, romain-gilliotte commented on packages/datasource-sql/package.json
> +    "ssh2": "^1.13.0"
Not installing @types/ssh2?

2023-06-21 15:16 UTC, romain-gilliotte commented on packages/datasource-sql/src/types.ts
> +
If you do the following, you get automatic documentation + allow users to use any alternative way to connect to the ssh server (password, ...)

(I'm omitting `sock` because you override it)

```suggestion
import { ConnectConfig } from 'ssh2';

export type SshOptions = Omit<ConnectConfig, 'sock'>;
```

2023-06-21 15:29 UTC, Scra3 commented on packages/datasource-sql/src/connection/errors.ts
> +  protected constructor(message: string, uri: string, details?: string) {
![image](https://github.com/ForestAdmin/agent-nodejs/assets/16675775/7a7616d5-4dc0-4d76-ae4d-72774363c5b7)

2023-06-21 15:48 UTC, Scra3 commented on packages/datasource-sql/src/connection/services/ssh-tunnel.ts
> +  private readonly clients = new Set<Client>();
There is two "clients" the client instantiate by the the "connect" and the forwarded socket. 
The first one is add in the "clients" and the other one in the "connectedClients"

2023-06-21 15:51 UTC, Scra3 commented on packages/datasource-sql/src/connection/services/socks-proxy.ts
> +      const serviceError = new SocksProxyServiceError(error as Error);
As you said, It s not the same level of abstraction. The service it s not seems to know that is the ssh connect fails. It can be bind to an other one, like an other proxy ... That why we have an other lever of error.

2023-06-22 07:21 UTC, Scra3 commented on packages/datasource-sql/src/connection/services/ssh-tunnel.ts
> +        this.sourceHost,
Nul is not an allowed value

2023-06-22 10:21 UTC, romain-gilliotte commented on packages/datasource-sql/src/connection/errors.ts
> +  protected constructor(message: string, uri: string, details?: string) {
et bah ok...

2023-06-28 13:26 UTC, romain-gilliotte approved these changes

2023-06-28 13:27 UTC, merged