feat(agent): no-code update record should handle errors correctly
ForestAdmin/agent-nodejs pull request #747
Opened 2023-06-23 10:48 UTC by Thenkei

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-06-26 11:59 UTC, realSpok commented
Nice !
<img width="499" alt="image" src="https://github.com/ForestAdmin/agent-nodejs/assets/19222576/efda518d-57b4-4b85-8aac-b693357b56a7">

2023-06-26 12:02 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +          `The no-code action ${action.name} cannot be triggered due to misconfiguration.` +
```suggestion
          `The no-code action ${action.name} cannot be triggered due to a misconfiguration.`
```
It is up for debate but we could remove the 'no-code'. From the user's perspective there are no difference between actions.

2023-06-26 12:02 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +          ` Please contact your administrator.\n(${error.name}: ${error.message})`,
The '\n' line break doesn't seem to be working. Do we need a <br/> ? or something else ?

2023-06-26 12:03 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +        `The no-code action ${action.name} cannot be triggered due to misconfiguration.` +
Same as above

2023-06-26 12:03 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +        `The no-code action ${action.name} cannot be triggered due to misconfiguration.` +
We could maybe factorize those 2 messages into a function

2023-06-26 12:05 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +    const fields = fieldsToUpdate.reduce((acc, fieldToUpdate) => {
I am not sure what `acc` stands for …

2023-06-26 12:06 UTC, realSpok requested changes
- ❗  Code review
  - ✅  Use pure functions when possible
  - ✅  Performance concerns
  - ✅  Security concerns
  - ✅  The PR tackle one subject only
- ✅ Automatic tests
  - ✅  Unit tests
  - ⤬  Integration tests
- ✅ Manual tests
  -  ✅ Test the functionality
  -  ✅ Test error cases
- ✅  PR title:
- ✅  Destination branch
- ✅  PR linked to the clickup task

2023-06-26 12:07 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +          `The no-code action ${action.name} cannot be triggered due to misconfiguration.` +
Even if the 'no-code' is a marketing term, I would say it is for the admins, not the users

2023-06-26 12:16 UTC, Thenkei commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +    const fields = fieldsToUpdate.reduce((acc, fieldToUpdate) => {
accumulator 😥

2023-06-26 12:24 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +    const fields = fieldsToUpdate.reduce((acc, fieldToUpdate) => {
ok. I guess I am also not very comfortable with reduce :)
But I get it now. You can leave it like that or write it as `accumulator`, as you prefer

2023-06-27 09:21 UTC, realSpok commented on packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
> +      return { ...fieldsAccumulator, [fieldToUpdate.fieldName]: fieldToUpdate.value };
`fieldsAccumulator` -> very straigthforward !

2023-06-27 09:42 UTC, merged