feat(config): configuration now allows to differenciate bucket path and database path
ForestAdmin/agent-nodejs pull request #752
Opened 2023-06-28 10:43 UTC by SteveBunlon

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-06-28 10:44 UTC, SteveBunlon commented on packages/plugin-aws-s3/src/types.ts
> +  storeAt?: <S extends TSchema = TSchema, N extends TCollectionName<S> = TCollectionName<S>>(
Some types are incorrect / missing here, work in progress

2023-06-28 10:45 UTC, SteveBunlon commented
Tests are missing, work in progress

2023-06-29 16:52 UTC, SteveBunlon commented on packages/plugin-aws-s3/src/types.ts
> +  storeAt?: <S extends TSchema = TSchema, N extends TCollectionName<S> = TCollectionName<S>>(
done

2023-07-04 09:44 UTC, romain-gilliotte requested changes

2023-07-04 17:43 UTC, SteveBunlon commented on packages/plugin-aws-s3/test/index.test.ts
> +          Key: 'books/null/myfile.txt',
This is an obvious bug that we'll need to fix. On create, upload of the file should be done in an after create hook, otherwise you won't get any record.id because it does not exist.

2023-07-05 07:15 UTC, merged