feat(datasource-replica): add replica datasource
ForestAdmin/agent-nodejs pull request #783
Opened 2023-08-01 09:48 UTC by SkyHuss

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/src/sequelize.ts
> +      // fixme
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/src/synchronization/cache-target.ts
> +    // fixme use something so that final users see the whole dump as a single transaction
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/src/synchronization/cache-target.ts
> +    // fixme use a transaction to wrap the whole thing
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/src/synchronization/cache-target.ts
> +        // fixme check that no pre-processing of the records are needed to handle
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/src/decorators/sync/collection.ts
> +    // FIXME need to handle many to many relationships here
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-sequelize/test/collection.test.ts
> +    // it('should serialize array of date as iso string', async () => {
👀

2023-08-08 09:56 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +// eslint-disable-next-line jest/no-commented-out-tests
👀

2023-08-10 13:50 UTC, jeffladiray requested changes

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +    });
```suggestion
    it('should insert the records by calling the delta only one time', async () => {
      const pullDeltaHandler: ReplicaDataSourceOptions['pullDeltaHandler'] = jest
        .fn()
        .mockResolvedValueOnce({
          more: false,
          newOrUpdatedEntries: [{ collection: 'contacts', record: { id: 3 } }],
          nextDeltaState: 'delta-state',
          deletedEntries: [],
        });

      const datasource = await makeReplicaDataSource({
        pullDeltaHandler,
        schema: makeSchemaWithId('contacts'),
        pullDeltaOnRestart: true,
      });

      expect(pullDeltaHandler).toHaveBeenCalledTimes(1);
      expect(await getAllRecords(datasource, 'contacts')).toEqual([{ id: 3 }]);
    });
```

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +  describe('when the delta has many iterations', () => {
Pretty sure all these needs to be refactored. I don't want the side effect of `getAllRecords` to introduce expect dependency

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-dump-delta.test.ts
> +      expect(await getAllRecords(datasource, 'contacts')).toEqual([
Same goes here, commenting
 ```
expect(await getAllRecords(datasource, 'contacts')).toEqual([
        { id: 1 },
        { id: 2 },
        { id: 3 },
      ]);
```
      
      shouldn't fail the test

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-dump.test.ts
> +      expect(await getAllRecords(datasource, 'contacts')).toEqual([]);
Expectation does not match the actual label of the test

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +import Croner from 'croner';
In all the following 3 tests, we should have a comment stating that `getAllRecords` trigger a list, thus call delta when it's on before access.

This is not "obvious" and makes some tests complex to read.

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-dump.test.ts
> +      expect(await getAllRecords(datasource, 'contacts')).toEqual([{ id: 1 }]);
A small comment on this test would be appreciated

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-dump.test.ts
> +      it('should error log or an error', async () => {
```suggestion
      it('should log an error', async () => {
```

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/push-delta.test.ts
> +import { getAllRecords, makeReplicaDataSource, makeSchemaWithId } from './factories';
To be reviewed, production of Arnaud M. and I

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/schema/flattener.test.ts
> +                fieldArray: [{ type: 'String' }],
This would throw as well with `field: { type: 'String'}` so not sure why this is under the `array` section ?

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +      pullDeltaOnBeforeAccess: true,
Typically, this is an issue where `getAllRecords` triggers a pull delta, thus the test isn't testing the pullDeltaOnSchedule

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/pull-delta.test.ts
> +      pullDeltaOnBeforeAccess: true,
```suggestion
      pullDeltaOnSchedule: '* * * * * *',
```

and 

```
    expect(await getAllRecords(datasource, 'contacts')).toEqual([]);
    expect(await getAllRecords(datasource, 'contacts')).toEqual([{ id: 1 }]);
```

just like mister Moncel did on his test. Still relying on dark magic though, to force tick() the agent

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/schema/flattener.test.ts
> +import { CollectionReplicaSchema, ReplicaDataSourceOptions } from '../../../src';
For these files, the test cases lgtm, but the way the describe are imbricated doesn't work.

It's worth reworking on those label and tests order.

2023-08-10 13:50 UTC, jeffladiray commented on packages/datasource-replica/test/integrations/schema/schema.test.ts
> +            { collection: 'contacts', record: { id: 1, name: 'f' } },
Having "good" test data would be key here, as when debugging, having something like "orest doesn't exist" feels like a totally different issue than the one this test would throw

2023-08-10 14:03 UTC, SkyHuss commented on packages/datasource-customizer/src/context/relaxed-wrappers/collection.ts
> +  get name(): string {
it's no, i'm removing it

2023-08-10 15:12 UTC, jeffladiray commented on packages/datasource-replica/test/unit/analysis-passthrought.unit.test.ts
> +
I'm still wondering why we can't integration test those lines.

2023-08-11 07:51 UTC, DayTF commented on packages/datasource-replica/src/options/flattener/schema.ts
> +  for (let i = output.length - 2; i >= 0; i -= 1) {
why is this -2 ? maybe we should define a named variable to explain ?

2023-08-11 10:03 UTC, jeffladiray approved these changes

2023-08-11 10:10 UTC, merged