feat: support date picker in action form widgets
ForestAdmin/agent-nodejs pull request #819
Opened 2023-09-12 08:20 UTC by realSpok

## Definition of Done
#85yxm8nvq
### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2023-09-13 12:19 UTC, ghusse commented on packages/datasource-customizer/src/decorators/actions/types/fields.ts
> +  widget: 'Date';
I think the name should reflect that the widget is asking for a date + time here

2023-09-13 12:19 UTC, ghusse commented on packages/datasource-customizer/src/decorators/actions/types/fields.ts
> +  minDate?: ValueOrHandler<Context, Date>;
why not simply `min` and `max`?

2023-09-13 12:22 UTC, ghusse requested changes
- ⚠️&nbsp;Code review
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; Performance concerns
  - ✅&nbsp; Security concerns
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
  - ✖️&nbsp; Integration tests
- ⚠️&nbsp;Manual tests
- ✅&nbsp;PR title
- ✅&nbsp;Destination branch
- ✅&nbsp;PR linked to the clickup task


I suggest renaming options `min` and `max`, and rename the Widget to `DateTimePicker` or `DateTime` to indicate that a time is also requested.

In addition to that, the current `minDate` property does not seem to work. I tested to provide a value but was able to select a date before this date in my form.

2023-09-13 13:19 UTC, realSpok commented on packages/datasource-customizer/src/decorators/actions/types/fields.ts
> +  minDate?: ValueOrHandler<Context, Date>;
I used the same name as in the date component on frontend side, for consistency

2023-09-13 14:55 UTC, ghusse commented on packages/agent/src/utils/forest-schema/action-fields.ts
> +  public static isDateInputField(
```suggestion
  public static isDateTimeField(
```

2023-09-13 14:55 UTC, ghusse commented on packages/datasource-customizer/src/decorators/actions/types/fields.ts
> +type DateInputFieldConfiguration<Context> = {
```suggestion
type DateTimeFieldConfiguration<Context> = {
```

2023-09-13 14:55 UTC, ghusse commented on packages/datasource-toolkit/src/interfaces/action.ts
> +export type ActionFieldDateInput = ActionFieldBase & {
```suggestion
export type ActionFieldDateTime = ActionFieldBase & {
```

2023-09-13 14:56 UTC, ghusse commented on packages/forestadmin-client/src/schema/types.ts
> +export type ForestServerActionFieldDateInputOptions = {
```suggestion
export type ForestServerActionFieldDateTimeOptions = {
```

2023-09-14 15:24 UTC, ghusse commented on packages/datasource-toolkit/src/interfaces/action.ts
> +export type ActionFieldDatePickerInput = ActionFieldBase & {
A declaration is missing on the type `ActionFieldWidget` below

2023-09-14 15:32 UTC, ghusse commented on packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
> +        minDate: field.min instanceof Date ? field.min.toDateString() : null,
```suggestion
        minDate: field.min instanceof Date ? field.min.toISOString() : null,
```

2023-09-14 15:33 UTC, ghusse commented on packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
> +              [`${parameter}Date`]: date.toDateString(),
It's better here to hardcode values, to repeating the same error twice: in the code and in tests.

2023-09-15 06:30 UTC, ghusse approved these changes
- ✅&nbsp;Code review
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; Performance concerns
  - ✅&nbsp; Security concerns
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
  - ✖️&nbsp; Integration tests
- ✅&nbsp;Manual tests
- ✅&nbsp;PR title
- ✅&nbsp;Destination branch
- ✅&nbsp;PR linked to the clickup task

2023-09-15 07:01 UTC, merged