feat: allow creation of agent without datasource
ForestAdmin/agent-nodejs pull request #910
Opened 2024-01-17 15:07 UTC by realSpok

## Definition of Done
#86bx3056z

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2024-01-22 10:17 UTC, Thenkei commented on packages/cloud-customizer/src/types.ts
> +export type Agent<S extends TSchema = TSchema> = {
👀

2024-01-22 10:17 UTC, Thenkei commented on packages/cloud-customizer/src/types.ts
> +export type Agent<S extends TSchema = TSchema> = {
Why just declaring a type?

2024-01-22 10:18 UTC, Thenkei commented on packages/cloud-customizer/src/services/typings-updater.ts
> +  agent.addDataSource(createSqlDataSource(`sqlite::memory:`, introspection));
Loving this <3

2024-01-22 10:23 UTC, realSpok commented on packages/cloud-customizer/src/services/typings-updater.ts
> +    fs.readFileSync('/Users/nicolas/Forest/cloud-customizer/introspection-sample.json', 'utf8'),
oups … let me fix that

2024-01-24 10:06 UTC, EnkiP approved these changes

2024-01-24 10:30 UTC, EnkiP approved these changes

2024-01-24 10:31 UTC, realSpok commented on packages/cloud-customizer/src/types.ts
> +export type Agent<S extends TSchema = TSchema> = {
it is outside the scope of this PR any. I moved it to this one:
https://github.com/ForestAdmin/agent-nodejs/pull/916

2024-01-24 11:26 UTC, Scra3 requested changes
waiting my push

2024-01-24 15:27 UTC, Scra3 approved these changes

2024-01-24 15:28 UTC, merged