feat: add version in introspection
ForestAdmin/agent-nodejs pull request #978
Opened 2024-02-06 15:21 UTC by EnkiP

## Definition of Done

### General

- [ ] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Test manually the implemented changes
- [ ] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

2024-02-06 16:22 UTC, Thenkei commented on packages/datasource-sql/src/index.ts
> +      : options?.introspection;
💪 You nailed it.

2024-02-06 16:24 UTC, Thenkei commented on packages/datasource-sql/src/index.ts
> +    }
This can only occurred in Cloud version. *

2024-02-07 08:30 UTC, Thenkei approved these changes
🚀

2024-02-07 08:31 UTC, Thenkei requested changes

2024-02-07 08:31 UTC, Thenkei commented on packages/datasource-sql/src/index.ts
> +    if (introspection.version > INTROSPECTION_FORMAT_VERSION) {
```suggestion
    if (introspection?.version > INTROSPECTION_FORMAT_VERSION) {
```

2024-02-07 13:12 UTC, Scra3 commented on packages/datasource-sql/src/index.ts
> +    if (introspection && introspection.version > INTROSPECTION_FORMAT_VERSION) {
you can reduce the condition by adding : **introspection?.version**

2024-02-07 14:49 UTC, EnkiP commented on packages/datasource-sql/src/index.ts
> +    if (introspection && introspection.version > INTROSPECTION_FORMAT_VERSION) {
I think it's less explicite: we intuitively don't know if undefined > 1 or not

2024-02-08 13:34 UTC, Scra3 commented on packages/datasource-replica/src/sequelize.ts
> +    tables: [],
Introspection is optional, you can probably avoid passing the argument.

2024-02-08 13:37 UTC, Scra3 commented on packages/datasource-sql/src/index.ts
> +      // This can only occur in CLOUD version, meaning that @forestadmin/datasource-sql should
not only in cloud version, user can pass an a legacy introspection in self hosted.

2024-02-08 14:09 UTC, Thenkei commented on packages/datasource-replica/src/sequelize.ts
> +    tables: [],
Nope, if you don't pass anything it tries to introspect. ^^'

2024-02-08 15:09 UTC, Scra3 commented on packages/datasource-sql/src/introspection/introspector.ts
> +  static getIntrospectionInLatestFormat(introspection?: Table[] | Introspection): Introspection {
Introspection | null ?

2024-02-08 15:46 UTC, Thenkei commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
What do you mean by SELF-HOSTED ?

2024-02-08 15:51 UTC, EnkiP commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
If a client has an agent with the last version of datasource-sql which is not yet deployed in the server, he'll get this error.

2024-02-08 15:54 UTC, EnkiP commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
oh no, he won't get the error but the server won't recognise his introspection right ? i'm not sure

2024-02-08 16:27 UTC, Thenkei commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
^^ In local, the users are likely not using cached introspection. 😄 

But you might be right. If they bump the version, compute an introspection, revert `datasource-sql` bump but still keep a locally cached introspection generated with the newer version this could occur.

2024-02-08 16:27 UTC, Thenkei commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
💪

2024-02-08 16:28 UTC, Thenkei commented on packages/datasource-sql/src/introspection/introspector.ts
> +        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but server still has
```suggestion
        - on SELF-HOSTED, client agent has the newer version of datasource-sql, but still has
```

2024-02-08 16:29 UTC, Thenkei commented on packages/datasource-sql/src/introspection/introspector.ts
> +          the old version. Client should downgrade datasource-sql.
```suggestion
          Client should downgrade datasource-sql.
```

2024-02-12 08:35 UTC, Thenkei approved these changes
- ✅&nbsp;Code review
  - ✅&nbsp; Use pure functions when possible
  - ✅&nbsp; The PR tackle one subject only
- ✅&nbsp;Automatic tests
  - ✅&nbsp; Unit tests
  - ✅&nbsp; Integration tests
- ✅&nbsp;Manual tests
- ✅&nbsp;PR title
- ✅&nbsp;PR linked to the clickup task

2024-02-12 08:48 UTC, merged